### ISSUE TITLE
FATAL EXCEPTION during PTC Login since yesterday, Server change? Account not banned, verified with client and new accounts

### ISSUE THREAD

**Issue by micha279** [Grover-c13/PokeGOAPI-Java#581] opened 2016-08-14 08:02 UTC
**Description:**
PTC Login fails since yesterday Aug 13, 2016 ~21 o'clock German time
Account NOT banned, verified with original client. Also tried new accounts, same issue

**Steps to reproduce:**
1. [Step 1]
Trying PTC Login in AsyncTask

```
protected String doInBackground(Void...arg0) {

        Log.d(TAG, "On doInBackground...");

        mPoGoClient = new OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .writeTimeout(10, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .build();

        Log.d(TAG, "Trying to login using PTC...");

        try {
            mPokemonGo = new PokemonGo(new PtcCredentialProvider(mPoGoClient, username, password), mPoGoClient, new SystemTimeImpl());
        }
        catch (LoginFailedException | RemoteServerException e) {
            Log.d(TAG, "PTC Login Failed with message: " + e.getMessage());
        }

        if (mPokemonGo != null)
            Log.i(TAG, "PTC Login Success");
}

```

**Expected behavior:**
PTC Login should return valid PokemonGo instance

**Actual behavior:**
PTC Login fails with FATAL Exception

**Stacktrace (If it's a crash):**
08-14 07:40:31.831 5903-6775/de.testApp.pokemanager D/LoginActivity: On doInBackground...
08-14 07:40:31.864 5903-6775/de.testApp.pokemanager D/LoginActivity: Trying to login using PTC...
08-14 07:40:36.210 5903-6840/de.testApp.pokemanager I/System.out: D/RequestHandler: Authenticated with static token
08-14 07:40:36.700 5903-6840/de.testApp.pokemanager E/AndroidRuntime: FATAL EXCEPTION: Async HTTP Thread
                                                                          Process: de.testApp.pokemanager, PID: 5903
                                                                          java.lang.NoSuchMethodError: No virtual method getByte(Ljava/lang/Object;J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
                                                                              at net.jpountz.util.UnsafeUtils.readByte(UnsafeUtils.java:68)
                                                                              at net.jpountz.xxhash.StreamingXXHash32JavaUnsafe.getValue(StreamingXXHash32JavaUnsafe.java:49)
                                                                              at com.pokegoapi.util.Signature.getLocationHash1(Signature.java:94)
                                                                              at com.pokegoapi.util.Signature.setSignature(Signature.java:35)
                                                                              at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:179)
                                                                              at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:221)
                                                                              at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
                                                                              at java.lang.Thread.run(Thread.java:818)
08-14 07:40:36.871 5903-5942/de.testApp.pokemanager E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7fe593e5abe0

**Version:**
PokeGOAPI-Java:2712436999

**Comment by AbandonedCart** [comment] 2016-08-14 08:13
https://github.com/Grover-c13/PokeGOAPI-Java/pull/501

**Comment by FabianTerhorst** [comment] 2016-08-15 19:18
Duplicate of #545

**Closed as completed by FabianTerhorst** 2016-08-15 19:18 UTC
