### ISSUE TITLE
version 0.4.1 doesn't works as well as before

### ISSUE THREAD

**Issue by AbandonedCart** [Grover-c13/PokeGOAPI-Java#726] opened 2016-08-30 20:04 UTC
From @tommywuhaojie:

After this new login, version 0.4.1 doesn't works as well as before. It throws exception almost every time when I login using both google key and PTC, So I have to roll back my App to use 0.4.0 API.

**Comment by PokeAlert** [comment] 2016-08-30 20:20
@tommywuhaojie and other having this problem please post a stackTrace

**Comment by gdespres** [comment] 2016-08-31 13:42
Same here !

I use TransferOnePidgeyExample with GoogleAutoCredentialProvider implementation. I have this exception one in three time : 

<pre>D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:156)
    at com.pokegoapi.api.PokemonGo.fireRequestBlock(PokemonGo.java:211)
    at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:168)
    at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
    at com.pokegoapi.examples.TransferOnePidgeyExample.main(TransferOnePidgeyExample.java:53)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
    ... 5 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:110)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:87)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 7 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:313)
    at java.lang.Thread.run(Thread.java:745)</pre>

**Comment by FabianTerhorst** [comment] 2016-08-31 14:05
That is just a null response from server.

**Comment by gdespres** [comment] 2016-08-31 14:35
maybe due to overloaded google servers ?
It's not everytime.

**Comment by FabianTerhorst** [comment] 2016-08-31 14:50
This exception is after the login.

**Comment by tommywuhaojie** [comment] 2016-08-31 18:19
I will post stackTrace later

**Comment by tommywuhaojie** [comment] 2016-09-02 06:09
@PokeAlert @LoungeKatt @FabianTerhorst StackTrace attached

Google Authentication Key Login:

I/System.out: D/RequestHandler: Authenticated with static token
W/System.err: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
W/System.err:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
W/System.err:     at com.pokegoapi.api.PokemonGo.fireRequestBlockOne(PokemonGo.java:210)
W/System.err:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:168)
W/System.err:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
W/System.err:     at com.xxxx.LoginActivity$5.run(LoginActivity.java:224)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
W/System.err:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
W/System.err:   ... 6 more
W/System.err: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.Observable.subscribe(Observable.java:9957)
W/System.err:     at rx.Observable.subscribe(Observable.java:9924)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
W/System.err:   ... 8 more
W/System.err: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
W/System.err:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
W/System.err:   ... 1 more
V/RenderScript: Application requested CPU execution

PTC Login:

W/System.err: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
W/System.err:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
W/System.err:     at com.pokegoapi.api.PokemonGo.fireRequestBlockOne(PokemonGo.java:210)
W/System.err:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:168)
W/System.err:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
W/System.err:     at com.xxxxx.LoginActivity$5.run(LoginActivity.java:254)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
W/System.err:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
W/System.err:   ... 6 more
W/System.err: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.Observable.subscribe(Observable.java:9957)
W/System.err:     at rx.Observable.subscribe(Observable.java:9924)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
W/System.err:   ... 8 more
W/System.err: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
W/System.err:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
W/System.err:   ... 1 more

**Comment by FabianTerhorst** [comment] 2016-09-02 06:23
That's only a null response from server

**Comment by tommywuhaojie** [comment] 2016-09-02 06:26
@FabianTerhorst I don't get exception if I use 0.4.0 API though

**Comment by tommywuhaojie** [comment] 2016-09-02 06:29
My Google login source code:

`
Thread networkThread = new Thread(new Runnable() {

```
        public void run() {
            OkHttpClient httpClient = new OkHttpClient();

            /**
             * Google:
             * You will need to redirect your user to GoogleUserCredentialProvider.LOGIN_URL
             * Afer this, the user must signin on google and get the token that will be show to him.
             * This token will need to be put as argument to login.
             */
            GoogleUserCredentialProvider provider = null;
            try {

                provider = new GoogleUserCredentialProvider(httpClient);

                if(google.isChecked()){
                    // google login
                    // we should be able to login with this token
                    String key = ((EditText) findViewById(R.id.google_key)).getText().toString().trim();
                    provider.login(key);

                    Log.d("DEBUG", "refresh token: " + provider.getRefreshToken());

                    Global.go = new PokemonGo(httpClient);
                    Global.go.login(provider); // login
                    ...`
```

**Comment by broach** [comment] 2016-09-02 22:31
The current Development branch is kinda screwy with Credential provider / PokemonGO construction. The initial login when you instantiate the PTCCredentialProvider always works, but then the PokemonGo.login() method is pretty much a crapshoot. Even when I introduce a 10 sec delay between those two things it will often hang, or throw an exception, or ... both (or, it just works and life is good). I've spent the last hour trying to debug it but it's hard because it _seems_ to be a timing issue; when I introduce breakpoints and step through ... it doesn't act badly.

**Comment by hanhmh1203** [comment] 2016-09-04 08:37
I got same problem :(.
How to fix it ?

**Comment by gdespres** [comment] 2016-09-04 08:55
You can use this dirty code pending a fix : 

```
PokemonGo go = ...
boolean logged = false;
int attempt = 1;
do {
    try {
        go.login(provider);
        logged = true;
    } catch(Exception e) {
        attempt++;
        if (attempt > 3) {
            throw e;
        }
    }
} while(!logged)
```

**Comment by broach** [comment] 2016-09-04 16:11
The problem is `ProkemonGo.login()` can end up firing multiple requests too fast and hitting the server rate limit. 

Basically, there's a pretty good chance the `GET_PLAYER` and `CHECK_CHALLENGE` requests will get processed by the `run()` loop in `RequestHandler` and then the requests created by `initialize()` (`DOWNLOAD_REMOTE_CONFIG_VERSION`, `CHECK_CHALLENGE`, `GET_HATCHED_EGGS`, `GET_INVENTORY`, `CHECK_AWARDED_BADGES`, `DOWNLOAD_SETTINGS`) get sent separately < 1 second later when the `run()` loop iterates again (it only has a 350ms delay). You end up getting back empty responses for all of them and then the API throws an unchecked 'AsyncPokemonGoException`. 

Adding a 5s delay in `.login()` before calling `initialize()` solves the issue but that's ugly. I'm thinking that the `run()` loop should simply have a minimum time to send in it to keep from doing this. 

Does anyone know the what the rate limiting time is these days? I only send map requests once per 10s, but I don't know what the game client is doing these days without setting up a MITM and checking it. 

As a side note - this also causes a memory leak.  The exception gets thrown in the loop in `sendServerRequests(ServerRequest... serverRequests)` on the first call to `.get()` on the first Obsevable. Because of this the other results are never removed from the `resultMap` (The removing of the response from the map happens inside get() in the Futures themselves, and none of the other futures are handled).

**Comment by mjmjelde** [comment] 2016-09-04 16:16
Get `GET_MAP_OBJECTS` has a rate limit of at least 10 seconds (you can see that in the settings if you do a `DOWNLOAD_SETTINGS` call).  All other calls do not really have a rate limit from what I can see.  The game client does the initial 5 login calls all within about two seconds (can be seen here: http://i.imgur.com/zVM1f7g.png)  

Also noticed that the time between `GET_MAP_OBJECTS` can very between 10 and 30 seconds.  Unsure why this happens.  Maybe the app can tell if you are moving or not... still unsure

**Comment by broach** [comment] 2016-09-04 17:23
"All other calls do not really have a rate limit from what I can see" ... except they do, demonstrated here :) 

I suspect the reason the calls in the png you posted are being made multiple times is that the game client is getting back the empty responses just like `initialize()` in the API currently does and then is re-trying.

**Comment by mjmjelde** [comment] 2016-09-04 17:42
None of the calls in the png are being made multiple times.  The first one is called twice only because its the one getting the rpc endpoint and once it gets that it has to make a new call.  All the other requests are unique and get valid responses.  These requests are the login requests that every client sends to get all the information it needs to play the game.

I'm more curious to see if multiple requests are being sent at the exact same time resulting in an invalid auth ticket to be send along with one of the request (or something similarly along these lines).

**Comment by broach** [comment] 2016-09-04 17:58
Multiples can't be sent at the exact same time by design; they're dropped into the RequestHandler's workQueue and then picked up on each iteration of the run loop. That said, 350ms isn't much of a delay. I added the "min time between requests" to the run loop in my local clone and that indeed does prevent the problem from occurring. I set it to 5s which is fine for my purposes, but I should probably see if there's a threshold closer to 1s

**Comment by broach** [comment] 2016-09-04 18:11
Yeah just a 1s minimum delay between the requests does the trick. Unmodified it will always fail for me if the requests get split over two iterations of the run loop.

**Comment by mjmjelde** [comment] 2016-09-04 19:34
A bit of debugging this error and I have the read error.  Most of the time when you get a null buffer error, you do get a response but the responses are null.  This means you do get a response envelope that has the error code in it.  When I call the login method and get the "Contents of buffer are null", the error in the envelope is "invalidPlatformRequest".  This means the signature was generated wrong with the request somehow.

**Comment by tommywuhaojie** [comment] 2016-09-20 05:56
use dirty code to solve the issues PokemonGo go = ...
boolean logged = false;
int attempt = 1;
do {
    try {
        go.login(provider);
        logged = true;
    } catch(Exception e) {
        attempt++;
        if (attempt > 3) {
            throw e;
        }
    }
} while(!logged)
I think you can close this issue @LoungeKatt

**Closed as completed** 2017-02-22 05:39 UTC
