### ISSUE TITLE
contents buffer are null

### ISSUE THREAD

**Issue by adobeSlash** [Grover-c13/PokeGOAPI-Java#331] opened 2016-07-29 06:19 UTC
**Description:**
Since this early morning I get an error when I try to getMapObjects..

**Stacktrace :**
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)

**Version:**
master

**Comment by a4andy** [comment] 2016-07-29 06:21
Check out #327

**Comment by Hindi** [comment] 2016-07-29 07:05
After updating to last revision on Development the problem is still there (the PR that should have fix it is merged with development).

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:83)

servers are fine.

**Comment by ramarro123** [comment] 2016-07-29 07:49
still not working for me, even after updating with the current PR

**Comment by Grover-c13** [comment] 2016-07-29 07:49
currently working on it #335

**Comment by vmarchaud** [comment] 2016-07-29 10:05
This exception is showed up when you make too much request per seconds, we have fixed our code that was throwing this, now all the java lib users need to verify that they dont send too much request.
Closing since the issue come from software using the java api, not the java api ifself.

**Closed as completed by vmarchaud** 2016-07-29 10:05 UTC

**Comment by Hindi** [comment] 2016-07-29 10:14
The exception is raised right after the login and comes from the constructor of the api.

**Comment by vmarchaud** [comment] 2016-07-29 10:18
From the latest revision on the dev branch, everyone is having a success construction, you shouldnt have problem, some people said that they maybe have put a rate-limit on IP too, so care that you didnt have multiple object constructed at the same time to be sure.

**Comment by Hindi** [comment] 2016-07-29 10:38
I made some test and still have null buffer thrown on catch pokemon sometime even if I wait for 300ms between catches.
Also, shouldn't the API handle this delay instead of the application? If it has to be done this way in order to work properly no matter what happens, then maybe the user shouldn't handle him himself.

**Comment by Grover-c13** [comment] 2016-07-29 10:44
Some people think it may be a limit per hour, i was going to collect some stats on it sometime

**Comment by vmarchaud** [comment] 2016-07-29 10:46
@Hindi If you had read what @Grover-c13 wrote in the first place, you'll know that we are working on this, it take time to write, pease be patient.

**Comment by Hindi** [comment] 2016-07-29 10:50
@vmarchaud I know it takes time and I don't want to annoy people but you've closed the issue and said it's working when it's not, that's all.

**Comment by DaveBben** [comment] 2016-07-30 13:44
Waiting for 500ms between calls of getDetails seems to make it work.

**Comment by apeshave** [comment] 2016-08-18 01:43
I am getting it when I am trying to log in itself.

Maybe I am doing something wrong.

`Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:111)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:88)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 7 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:298)
    at java.lang.Thread.run(Unknown Source)
`

**Comment by vamidi** [comment] 2017-06-14 12:08
Hi i am new to the Pokego-java api. I am trying to make an connection but getting this error aswell is there already a fix yet? Is there also someone that can tell me about if they changed the secret so that nobody can login?

Last question
is there also someone that can explain how the api works in general. like example how to make a simple connection yourself. (maybe not a place to say it here in this comment section)
