### ISSUE TITLE
Error when using GoogleAutoCredentialProvider

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#582] opened 2016-08-14 09:47 UTC
When i instanciate GoogleAutoCredentialProvider, i have this exception : 
`java.lang.NoClassDefFoundError: Failed resolution of: Lsvarzee/gps/gpsoauth/Gpsoauth;`

I tested this with an oldest jar of the api, it's working, so there is an issue in the latest version of the api.

This is my code : 

```
OkHttpClient httpClient = new OkHttpClient();
        GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient, username, password);
        PokemonGo go = new PokemonGo(provider, httpClient);
```

**Comment by AbandonedCart** [comment] 2016-08-14 09:49
Add `compile 'svarzee.gps:gpsoauth:0.3'` to gradle.build under `dependencies`

**Comment by meher19** [comment] 2016-08-14 10:43
This resolved the Lsvarzee error, but the auth still not working, when i debug my app a problem occurs in the class  Gpsoauth.java in this line : 
`return httpClient.newCall(request).execute();`
When i reach this line there is no triggered exception, but there is no response from the call, the debugger still blocked in this line.

**Comment by AbandonedCart** [comment] 2016-08-14 10:49
There was only a slight chance importing that dependency would override the one from the library. You'd have to build the library to resolve the issue of that didn't work.

**Comment by meher19** [comment] 2016-08-14 11:10
i checked this when debugging my app, it's using the Gpsoauth class from the imported dependency, i checked too if this class exists in the api but nothing.

**Comment by FabianTerhorst** [comment] 2016-08-15 18:42
Could you resolve your problem?

**Comment by FabianTerhorst** [comment] 2016-08-15 19:26
Close this for now looks unrelated to this library.

**Comment by meher19** [comment] 2016-08-17 09:41
No, i not resolved my problem

**Comment by FabianTerhorst** [comment] 2016-08-17 11:48
We need an updated jcenter dependencie to better debug this.

**Comment by AbandonedCart** [comment] 2016-08-17 11:48
`httpClient.newCall(request).execute();` is most likely being implemented incorrectly.
See https://github.com/Grover-c13/PokeGOAPI-Java#usage-example-mostly-how-to-login-
and https://github.com/Grover-c13/PokeGOAPI-Java/tree/Development/sample/src/main/java/com/pokegoapi/examples

**Comment by meher19** [comment] 2016-08-17 11:56
@LoungeKatt The example is showing the usage of GoogleUserCredentialProvider, but in my case i try to use the GoogleAutoCredentialProvider which is different, this auth mode worked in previous versions of the API but now i think there is a regression in the last version.
The line `httpClient.newCall(request).execute();` is in the class Gpsoauth.java from the API source code, by debugging this class i noticed that's the problem occurs in this call.

**Comment by AbandonedCart** [comment] 2016-08-17 12:00
The reason only one example is shown is that each credential provider is designed to follow the same structure. The issue is that you appear to be attempting to recreate the inner functionality locally.

**Comment by meher19** [comment] 2016-08-17 12:03
No i'm just trying to use the credentials provider as shown in the example, look at my first post it's contains my source code.

**Comment by AbandonedCart** [comment] 2016-08-17 12:08
Then there should be no issue with Gpsoauth, since that is an external dependency handled by the API library. You should verify you are using the library-all file that includes the dependencies.

Perhaps it would be best to wait for the bintray build of the library to update, since the problem appears to be specific to your build of the library.

**Comment by meher19** [comment] 2016-08-17 13:23
now i'm using the PokeGOAPI-library-0.4.0.jar that's i builded from a clean clone of the API source code, this jar does not contains svarzee.gps dependency required by the the API, resulting of the error i described in a earlier post.
In the previous versions of the API the dependecy was included, i can't understand why the developors removed it in the last version.
So i added the depenency in my project to resolve the problem, but i can't figure out why it's still not working like it was when the dependecy was included in the API, this is the question..

**Comment by AbandonedCart** [comment] 2016-08-17 13:33
You want `PokeGOAPI-library-all-0.4.0.jar`. This is the **exact** name of the file.
The developers did not remove the dependency, you are using the wrong file.

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/build.gradle#L94

**Comment by meher19** [comment] 2016-08-18 10:26
ok this resolved my problem, now i still getting 0 results from the getCatchablePokemon method, look at https://github.com/Grover-c13/PokeGOAPI-Java/issues/513 issue

**Comment by meher19** [comment] 2016-08-18 11:08
Update : i tried also with a new Ptc account, and i added DeviceInfo a SensorInfo data to PokemonGo object but it still returning 0 results.

**Comment by FabianTerhorst** [comment] 2016-08-18 11:09
you know what sensorinfo needs for the values?

**Comment by meher19** [comment] 2016-08-18 11:11
`sensorInfo.setAccelNormalizedZ(0);`
It needs more values ?

**Comment by FabianTerhorst** [comment] 2016-08-18 11:12
We don´t know what to set for the other values.

**Comment by meher19** [comment] 2016-08-18 11:14
Ok so the API is still not working ?

**Comment by meher19** [comment] 2016-08-18 11:49
Can you reopen the issue https://github.com/Grover-c13/PokeGOAPI-Java/issues/513 ?
Because the problem is still not resolved.

**Comment by AbandonedCart** [comment] 2016-08-18 12:17
You need to add a delay between calls.

This is definitely not the API to use for learning gradle or Java. If you are unfamiliar with either, it would be much better to familiarize yourself with both and come back when you are ready. Time spent trying to diagnose personal implementation issues is taken directly from the time spent improving the API, possibly even to prevent them. Just something to consider.

**Comment by meher19** [comment] 2016-08-18 12:45
I don't like the way you talk to me, i'm a Java and Maven expert, but i never used Gradle before.
My objective is not to learn programming but to create an Android app.
Some problems i reported are not a personal implementation issues, so it helps improving the API and resolve bugs. For personal implementation questions : if you have no time to respond to them just don't do it, it's better than being disagreeable

I already have a one second delay between calls, so i insist about the existance of an issue.

**Comment by AbandonedCart** [comment] 2016-08-18 12:58
Your issues so far have been with not following the README, so it is not unrealistic to think you may be inexperienced. If you are an expert, then I will leave it in your capable hands to diagnose the issue and propose a solution. Until then, it has not been reproduced by enough users to suggest it is an issue with the API and not something in your personal implementation.

**Comment by meher19** [comment] 2016-08-18 13:41
I have got the same code working in the past, until the Niantinc server update which broke tha API, i reported this issue in https://github.com/Grover-c13/PokeGOAPI-Java/issues/513. The server update needed some changes in the API to (supposed) make it work again, but even after updating the library the problem still not resolved.
Check the https://github.com/Grover-c13/PokeGOAPI-Java/issues/513 history, you will see there is 3 other users experiencing the same issue, no one of them have resolved his problem. So i'm far being the only one experiencing this issue, you have to check all the history before to say sush things.

**Comment by FabianTerhorst** [comment] 2016-08-18 13:42
Maybe there server wants the correct sensor infos.

**Comment by meher19** [comment] 2016-08-18 13:49
@FabianTerhorst maybe, after last updates the official app is now checking if the fake gps mode is enabled in the device settings, if true the server send back an empty data, so we need to know which attribute the server uses to check this, are you sure this attribute is in the SensorInfo object ?

**Comment by FabianTerhorst** [comment] 2016-08-18 13:51
no its not. But we are faking an ios device so we don´t need this.

**Comment by AbandonedCart** [comment] 2016-08-18 14:12
@meher19 I have checked the history. While I understand you may be hostile over how you took my original comment, you also have to consider that 3 users experiencing a similar issue is still a localized issue. The probability of 3 in 100 people doing the same thing incorrectly is still quite high.

The server does not need an attribute to check if fake GPS is enabled on the device. That is a simple matter of whether or not sensor info exists according to the device sending it.

**Comment by meher19** [comment] 2016-08-18 14:24
This is the actual state of my code :

```
DeviceInfo deviceInfo = DeviceInfo.DEFAULT;
        go.setDeviceInfo(deviceInfo);
        SensorInfo sensorInfo = new SensorInfo();
        sensorInfo.setAngleNormalizedZ(0);
        go.setSensorInfo(sensorInfo);
```

If you have any suggestion i can try it.

**Comment by AbandonedCart** [comment] 2016-08-18 14:30
Testing checklist:
- Add a delay between login and first call (this includes something trivial, such as username)
- Increase the delay between calls to 10 seconds (the minimum for map calls)
- Make a single call for objects (or call the objects as a single object and then separate locally)
- Set device information before making the first call
- Leave time between tests where you do not connect at all (Official client or test code)
- Try alternate accounts and IPs (such as connecting through wifi and 4g)

If you get positive results at any point, then you know where the issue lies.

**Comment by FabianTerhorst** [comment] 2016-08-18 14:32
@meher19 i don´t have any jailbreaked ios device to get better informations for the sensorinfos. I just know there are incomplete.

**Comment by meher19** [comment] 2016-08-18 14:51
@LoungeKatt 
I increased the delays to 10 seconds, but still not working, this is my full code : 

```
public List<EncounterResult> lookupPoke(String username, String password) throws InterruptedException, LoginFailedException, RemoteServerException, Exception, RuntimeException {
        OkHttpClient httpClient = new OkHttpClient();

        GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient, username, password);

        PokemonGo go = new PokemonGo(provider, httpClient);

        SECONDS.sleep(10);

        DeviceInfo deviceInfo = DeviceInfo.DEFAULT;
        go.setDeviceInfo(deviceInfo);

        SensorInfo sensorInfo = new SensorInfo();
        sensorInfo.setAngleNormalizedZ(0);
        go.setSensorInfo(sensorInfo);

        // After this you can access the api from the PokemonGo instance :
        go.setLocation(location.getLongitude(), location.getLatitude(), 0); // set your position to get stuff around (altitude is not needed, you can use 1 for exemple)
        List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon(); // get all currently catchables pokemons around you
        List<EncounterResult> encounterResults = new ArrayList<EncounterResult>();

        for (CatchablePokemon cp : catchablePokemon) {
            // You need to Encounter first.
            EncounterResult encResult = (EncounterResult) cp.encounterPokemon();
            // if encounter was succesful, catch
            if (encResult.wasSuccessful()) {
                encounterResults.add(encResult);
            }
            SECONDS.sleep(10);
        }

        return encounterResults; // get all currently catchables pokemons around you
    }

```

**Comment by FabianTerhorst** [comment] 2016-08-18 14:52
Can you try to remove the sensorinfo set, because there are not fully set.

**Comment by AbandonedCart** [comment] 2016-08-18 14:54
```
public List<EncounterResult> lookupPoke(String username, String password) throws InterruptedException, LoginFailedException, RemoteServerException, Exception, RuntimeException {
        OkHttpClient httpClient = new OkHttpClient();

        GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient, username, password);

        PokemonGo go = new PokemonGo(provider, httpClient);
        DeviceInfo deviceInfo = DeviceInfo.DEFAULT;
        go.setDeviceInfo(deviceInfo);
        SensorInfo sensorInfo = new SensorInfo();
        sensorInfo.setAngleNormalizedZ(0);
        go.setSensorInfo(sensorInfo);

        SECONDS.sleep(10);

        // After this you can access the api from the PokemonGo instance :
        go.setLocation(location.getLongitude(), location.getLatitude(), 15); // set your position to get stuff around (altitude is not needed, you can use 1 for exemple)

        SECONDS.sleep(10);

        List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon(); // get all currently catchables pokemons around you
        List<EncounterResult> encounterResults = new ArrayList<EncounterResult>();

        SECONDS.sleep(10);

        for (CatchablePokemon cp : catchablePokemon) {
            // You need to Encounter first.
            EncounterResult encResult = (EncounterResult) cp.encounterPokemon();
            // if encounter was succesful, catch
            if (encResult.wasSuccessful()) {
                encounterResults.add(encResult);
            }
            SECONDS.sleep(10);
        }

        return encounterResults; // get all currently catchables pokemons around you
    }

```

**Comment by FabianTerhorst** [comment] 2016-08-18 14:55
set location is not a network call or?

**Comment by AbandonedCart** [comment] 2016-08-18 14:58
It's not. It sets it for the next call. 
It's not production code, just testing ridiculous delays.

**Comment by meher19** [comment] 2016-08-18 15:27
location is set by another method, it gets current gsp location from my android device which i faked to be sure to have some pokemons. I checked location objet in debug it contains the good value.

@FabianTerhorst i removed SensorInfo still not working.
@LoungeKatt i tested your code always 0 data returned.

**Comment by FabianTerhorst** [comment] 2016-08-18 15:33
for me its working with the sample code.

**Comment by FabianTerhorst** [comment] 2016-08-18 15:33
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/sample/src/main/java/com/pokegoapi/examples/CatchPokemonAtAreaExample.java

**Comment by FabianTerhorst** [comment] 2016-08-18 15:34
Im getting 4 pokemons back.

**Comment by meher19** [comment] 2016-08-22 11:26
it's finally works, it was a problem in my gps location format.
so we do not need DeviceInfo and SendorInfo objects, and only 1 second delay is enought to make it work.

**Closed as completed** 2016-08-22 11:27 UTC
