### ISSUE TITLE
Walking between geolocations

### ISSUE THREAD

**Issue by leandrolimasi** [Grover-c13/PokeGOAPI-Java#612] opened 2016-08-17 04:56 UTC
**Description:**
It is now possible to set the geoLocaltion, OK its nice. But how can I go from one location to another location walking/running ? With the API it is possible? Since it brings me to distance until pokestops I wanted to go from a to another without the Geolocation to set a one time.

**Steps to reproduce:**
Any

**Expected behavior:**
Walking between geoLocations.

**Actual behavior:**
Any

**Stacktrace (If it's a crash):**

**Version:**
0.4.0

**Comment by FabianTerhorst** [comment] 2016-08-17 05:00
Duplicate of.#586

**Comment by FabianTerhorst** [comment] 2016-08-17 05:00
Duplicate of.#586

**Closed as completed by FabianTerhorst** 2016-08-17 05:00 UTC
