### ISSUE TITLE
The API prints stacktraces, instead of throwing errors

### ISSUE THREAD

**Issue by Nickforall** [Grover-c13/PokeGOAPI-Java#45] opened 2016-07-19 17:41 UTC
An API should always throw the exception to the user, instead of just printing a stack and ignoring it.

Example:

``` Java
        try {
            go = new PokemonGo(auth, http);
        } catch(Exception ex) {
            Logger.error("Servers appear to be down");
            ex.printStackTrace();
            System.exit(1);
        }
```

Won't do shit, because you only print the stack, which makes it impossible for the API user to handle errors while the servers are down...

**Comment by martinzlocha** [comment] 2016-07-19 17:52
Fork, Fix, Pull request :)

**Comment by jabbink** [comment] 2016-07-19 17:57
Duplicate of #43

**Closed as completed by jabbink** 2016-07-19 17:57 UTC
