### ISSUE TITLE
API stopped working at 14/02/2017

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#863] opened 2017-02-14 23:28 UTC
**Description:**
Just a few minutes ago, the API stopped working, I can no longer login with any account (PTC, Google, Token), please someone who can help me. I add an image of the exception that I get in the console. Thanks in advance,

**Version:**
I'm using the last commited changes of the API. Thanks in advance!

![captura de pantalla 2017-02-14 a las 5 24 59 p m](https://cloud.githubusercontent.com/assets/803683/22954260/04b6a6ba-f2db-11e6-90c2-e171cfe0e5d3.png)

**Comment by tommywuhaojie** [comment] 2017-02-15 03:57
Same here... Can someone please help

**Comment by vokhanhhuy** [comment] 2017-02-15 05:06
same here, please help!

**Comment by karaopea** [comment] 2017-02-15 05:16
Dear Friends, I have same problem.
but this api is running well, you have to handle the exception.

// login try code
 catch (Exception e) {
                    return  ; // don't care
  }

good luck.

EDIT:
Now you can't available google account info.

**Comment by vagprogrammer** [comment] 2017-02-15 16:13
Hi @gegy1000 now I can login normally. What happened? Why did you reopened this issue?

**Comment by RebliNk17** [comment] 2017-02-15 16:16
The problem is partially resolved,
there is still a problem with the working flow of the api now.
@gegy1000 is working on a fix.

**Comment by vagprogrammer** [comment] 2017-02-15 16:23
Ok, thank you so much =). Will be pending!

**Comment by Gegy** [comment] 2017-02-15 17:18
I misinterpreted the problem - we are missing a blank request sent at login, which means I have to rework the request system a bit. The current request system could not work cleanly with a blank request.

**Comment by Raventy** [comment] 2017-02-16 21:25
Hi,

Not sure if it is caused by the same blank request problem, using the latest API code, it happens too when calling catchablePokemon.catchPokemon(catchOptions);

com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:81)
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:79)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:47)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:566)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:356)
	[trace deleted]
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:120)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:97)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:173)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:130)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:100)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon$6.call(CatchablePokemon.java:667)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon$6.call(CatchablePokemon.java:649)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:75)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	... 35 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:89)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:381)
	at java.lang.Thread.run(Unknown Source)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.google.protobuf.ByteString$LiteralByteString.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:75)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:566)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:356)
	[Trace deleted]

**Comment by Gegy** [comment] 2017-02-19 15:23
This should be fixed on my fork. Will merge after tested more.

**Closed as completed** 2017-02-22 05:39 UTC
