### ISSUE TITLE
Get location from nearby pokemon

### ISSUE THREAD

**Issue by RootSoft** [Grover-c13/PokeGOAPI-Java#470] opened 2016-08-03 13:04 UTC
I'm wondering if there a way to get the location (latitude, longitude) from a nearby pokemon?

`ArrayList<NearbyPokemon> nearbyPokemon = new ArrayList<>(pokemonGo.getMap().getNearbyPokemon());`

**Comment by FabianTerhorst** [comment] 2016-08-03 13:36
A nearby pokemon is only returning the distance.

**Comment by FabianTerhorst** [comment] 2016-08-03 13:37
duplicate of #414

**Comment by RootSoft** [comment] 2016-08-03 14:08
If i may ask, how do maps like pokevision, pokemaps, etc find and display the location of pokemon around you?

**Comment by jabbink** [comment] 2016-08-03 14:12
Triangulation. Which has been patched a week ago.

They just request multiple map tiles by teleporting. Wild and Map Pokemon do have exact coordinates.

**Closed as completed by jabbink** 2016-08-03 14:12 UTC
