### ISSUE TITLE
Auth token not refreshing?

### ISSUE THREAD

**Issue by Jazed** [Grover-c13/PokeGOAPI-Java#540] opened 2016-08-10 11:31 UTC
Sometimes it fixes itself after about 10 seconds, sometimes completely breaks.

```
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 7 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
    ... 1 more
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.api.map.fort.Pokestop.loot(Pokestop.java:172)
    at com.jazed.pogobot.handlers.PokestopHandler.lootPokeStop(PokestopHandler.java:67)
    at com.jazed.pogobot.handlers.PokestopHandler.checkForPokeStops(PokestopHandler.java:40)
    at com.jazed.pogobot.tasks.UpdateTask.run(UpdateTask.java:21)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
    ... 5 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 7 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
    ... 1 more
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.api.map.fort.Pokestop.loot(Pokestop.java:172)
    at com.jazed.pogobot.handlers.PokestopHandler.lootPokeStop(PokestopHandler.java:67)
    at com.jazed.pogobot.handlers.PokestopHandler.checkForPokeStops(PokestopHandler.java:40)
    at com.jazed.pogobot.tasks.UpdateTask.run(UpdateTask.java:21)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
    ... 5 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 7 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
    ... 1 more
```

**Comment by jabbink** [comment] 2016-08-10 20:38
Google/PTC?

properties/JSON?

**Comment by Jazed** [comment] 2016-08-10 22:59
I'm using PTC, and a self written bot.

**Comment by broach** [comment] 2016-08-11 00:14
I've seen this quite a bit, it's probably the PTC auth servers puking (that happens a _lot_)

**Comment by gdespres** [comment] 2016-08-14 09:40
GoogleAutoCredentialProvider.java [line 111] : 

public boolean isTokenIdExpired() {
     return tokenInfo.authToken.getExpiry() > time.currentTimeMillis() / 1000 - 60;
}

token expired if lower than currentTimeMillis / 1000 ? no ?
I think this code is better : 

public boolean isTokenIdExpired() {
     return tokenInfo.authToken.getExpiry() < time.currentTimeMillis() / 1000;
}

**Comment by FabianTerhorst** [comment] 2016-08-15 20:36
Duplicate of #474

**Closed as completed by FabianTerhorst** 2016-08-15 20:36 UTC
