### ISSUE TITLE
Wrong default spin modifier?

### ISSUE THREAD

**Issue by gsisso** [Grover-c13/PokeGOAPI-Java#640] opened 2016-08-19 14:14 UTC
**Description:**
Seem like the recent commits are not the same as the old code

this is the old line - 
https://github.com/Grover-c13/PokeGOAPI-Java/commit/25ffc8570e21a772c9522e33f6a9a14bcf28b32a#diff-d42b1ba6ad3d7f4180f9a64f3ad54e55L619

you can clearly see that the old spin modifier was 

`0.85 + Math.random() * 0.15`

while the new one ( https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/settings/CatchOptions.java#L78 ) is - 

`Math.random() * 0.15`

is it on purpose like this ? why not using the same old values ?

also it seem like the 'index' variable on getItemBall() method causing more issues then actually helping,can anyone explain the point of it?

**Comment by LoungeKatt** [comment] 2016-08-19 15:21
What issues is the index variable causing? You should not be modifying it at all.

**Comment by AbandonedCart** [comment] 2016-08-19 15:24
Spin value fixed by https://github.com/Grover-c13/PokeGOAPI-Java/pull/641

**Comment by AbandonedCart** [comment] 2016-08-19 15:33
The purpose of the index is behind the scenes. Due to the possible confusion about relative parameters, this exact scenario is what was mentioned in the readme. It is meant to allow you to customize the starting / ending point of selecting a ball based on inventory.

If you enable the option to get the best ball, it will prevent the lowest ball from dropping below your pokeball setting, for example a Great Ball. You will start at the Master Ball and move down.
If you do not opt for strict ball type or best ball, it will also serve to pick the starting ball to move up from. For example, setting Great Ball will start there and move up.
If you do opt for a strict ball type, it will only attempt to use the specific ball specified.

Regardless, it is not something that is modified by the user. It is a private index to allow the code to pick a ball. If you are trying to pick a specific ball, then set the ball and enable strict type.

**Closed as completed by AbandonedCart** 2016-08-19 15:33 UTC

**Comment by gsisso** [comment] 2016-08-19 15:39
@LoungeKatt thanks for the fast fixing. the issue with that index part that lets say I want it to start from great ball instead of pokeball when I'll ran out of great ball & ultra ball it will throw no such item but I might have pokeballs left.

**Comment by AbandonedCart** [comment] 2016-08-19 15:43
The entire conversion is relatively new, so before jumping on trying to "fix" it, why not take a little time and try to use it first? You may find that the issue isn't it being broken, just a lot of previously broken things finally working the way they were intended. 

Not throwing any ball in your inventory when you tell the API to only use a Great Ball is a perfect example. The old code made an attempt at throwing that ball, then just started throwing whatever the next one up / down was until one hit. There was no real option for saying "just this one, then give up and tell me you couldn't"

if what you are looking to do is override those settings for a "throw at all costs" scenario, I have put together https://github.com/Grover-c13/PokeGOAPI-Java/pull/642 with the additional option of discarding restrictions.

**Comment by LoungeKatt** [comment] 2016-08-19 15:49
The entire conversion is relatively new, so before jumping on trying to "fix" it, why not take a little time and try to use it first. You may find that the issue isn't it being broken, just a lot of previously broken things finally working the way they were intended. 
Not throwing any ball in your inventory when you tell the API to only use a Great Ball is a perfect example. The old code made an attempt at throwing that ball, then just started throwing whatever the next one up / down that was laying around until one hit. There was no real option for saying "just this one, then give up and tell me you couldn't"
