### ISSUE TITLE
Error instant run android

### ISSUE THREAD

**Issue by john086** [Grover-c13/PokeGOAPI-Java#310] opened 2016-07-28 12:42 UTC
Any idea?

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
> Error:Error converting bytecode to dex:
> Cause: Dex cannot parse version 52 byte code.
> This is caused by library dependencies that have been compiled using Java 8 or above.
> If you are using the 'java' gradle plugin in a library submodule add 
> targetCompatibility = '1.7'
> sourceCompatibility = '1.7'
> to that submodule's build.gradle file.

**Comment by FabianTerhorst** [comment] 2016-07-28 12:43
you enabled multidex? Multidex doesn't support instant run.

**Comment by john086** [comment] 2016-07-28 12:47
I disabled but had the same error.

**Comment by louisditzel** [comment] 2016-07-28 12:49
https://github.com/svarzee/gpsoauth-java/pull/1

Dependency currently relies on Java 8, which the normal Android compiler doesn't yet support. When this is merged everything should work again. Until then I'd roll back to a previous commit or use the release build.

**Comment by john086** [comment] 2016-07-28 12:52
Which commit i can use? of PokeGOAPI-Java ?

**Comment by louisditzel** [comment] 2016-07-28 12:56
`compile 'com.github.Grover-c13:PokeGOAPI-Java:b0f594e2c2'` 

Thats the commit before the one introducing the bug, should be fine. Replace the line in your gradle build file with that.

**Comment by vmarchaud** [comment] 2016-07-28 13:01
The problem is that you cant login with google on these build, but you should be able to compile at least.

**Comment by john086** [comment] 2016-07-28 13:07
Soo   error: cannot find symbol class GoogleAutoCredentialProvider , there is no fix programmed?

**Comment by benjy3gg** [comment] 2016-07-28 13:07
did you guys get login working with the library?
i only an error "BadAuthentication" on Android and i'm using the code from the pullrequest!

**Comment by john086** [comment] 2016-07-28 13:08
with latest pull my code don't run give error in the first post

**Comment by vmarchaud** [comment] 2016-07-28 13:10
Google login arent working today, and `GoogleAutoCredentialProvider` introduced your bug, its logic that if you get the commit before the class isnt here.

**Comment by john086** [comment] 2016-07-28 13:11
It's resolved this errore can close it

**Comment by vmarchaud** [comment] 2016-07-28 21:48
centralized issue in #326

**Closed as completed by vmarchaud** 2016-07-28 21:48 UTC

**Comment by vaibhavthapliyal** [comment] 2016-07-29 15:34
How was this issue resolved? Can someone guide me through this. I am using this dependency:

com.github.Grover-c13:PokeGOAPI-Java:dcaa793557

**Comment by vmarchaud** [comment] 2016-07-29 15:34
@vaibhavthapliyal Check the issue that i linked, it isnt resolved yet.

**Comment by vaibhavthapliyal** [comment] 2016-07-29 15:41
So, till this issue is resolved, which build can I use for a successful login with google and also bypass this instant run error?
