### ISSUE TITLE
[Android][Error] NoSuchMethodError()

### ISSUE THREAD

**Issue by cesco89** [Grover-c13/PokeGOAPI-Java#545] opened 2016-08-10 19:59 UTC
On some devices i get NoSuchMethodError() that causes the app to force close.
The lib is up-to-date with the last commit on this repo.

Here's the stack trace:

`java.lang.NoSuchMethodError: No virtual method getByte(Ljava/lang/Object;J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
    at net.jpountz.util.UnsafeUtils.readByte(UnsafeUtils.java:68)
    at net.jpountz.xxhash.StreamingXXHash32JavaUnsafe.getValue(StreamingXXHash32JavaUnsafe.java:49)
    at com.pokegoapi.util.Signature.getLocationHash1(Signature.java:91)
    at com.pokegoapi.util.Signature.setSignature(Signature.java:37)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:179)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:221)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
    at java.lang.Thread.run(Thread.java:818)`

Is there a workaround for this? Thanks

**Comment by FabianTerhorst** [comment] 2016-08-10 20:00
checkout #501

**Comment by kaiyan910** [comment] 2016-08-11 13:40
I have the same issue, I have already set minifyEnabled to false but user using ASUS still reporting a app crash

**Comment by cesco89** [comment] 2016-08-11 14:45
i've already checked out [#501](https://github.com/Grover-c13/PokeGOAPI-Java/pull/501)
but the only way i found to get the app working without causing crashes everywhere (or at least on all devices with OS version < 6.0) was to revert to an older version of the library (without "UnSafe")

**Comment by kaiyan910** [comment] 2016-08-11 15:06
@cesco89 can you tell me which version are you using ? thanks

**Comment by cesco89** [comment] 2016-08-11 15:21
i can't tell you which is the exact version because i've precompiled it some days ago, but should be a build made with commits from 5-6 August

**Comment by kaiyan910** [comment] 2016-08-12 16:42
nvm i just copy the changes from #501 and compile a new jar it works now, thanks :D

**Comment by cesco89** [comment] 2016-08-12 19:17
@kaiyan910 so, if you pull from repo and merge also that commit, adding the flag for proguard, the Lib works without issues?

**Comment by kaiyan910** [comment] 2016-08-13 00:32
@cesco89 I didn't enable the proguard so I am not sure it works with proguard or not, but at least it works without the proguard enable

**Comment by FabianTerhorst** [comment] 2016-08-15 20:39
Duplicate of #499

**Closed as completed by FabianTerhorst** 2016-08-15 20:39 UTC
