### ISSUE TITLE
[Question] Correct way to integrate API code (seen issues performing login step using jitpack+gradle dependency and jar built).

### ISSUE THREAD

**Issue by JesusM** [Grover-c13/PokeGOAPI-Java#210] opened 2016-07-25 11:28 UTC
**Description:**
I've been trying to integrate this API in an Android app without a "successful" result so maybe someone could tell me what's my error (sorry in advance if this is not the proper place to ask this but I haven't seen any FAQ and the code I'm using is the one the samples provide (but handling threads correctly)).
Right now (and please correct me if I'm wrong) the API can be consumed using jitpack.io + gradle and building the code provided to obtain jar library.
- Using the gradle dependency through jitpack.io (`compile 'com.github.Grover-c13:PokeGOAPI-Java:4831b9f5653a0d7945849ab3dc028b5d728ce488'` to point over latest commit in `Development`). 
  However, when creating the player profile in the PTC login flow, I'm receiving this error:

```
com.pokegoapi.exceptions.RemoteServerException: Received malformed response : com.google.protobuf.InvalidProtocolBufferException: CodedInputStream encountered a malformed varint.
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:125)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
```
- Building the code provided (using `./gradlew build bundle` command) to obtain the .jar file and using it as a library to my Android code, I find next error when performing PTC login:

```
/com.omkarmoghe.pokemap W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=2; index=327112256
/com.omkarmoghe.pokemap W/System.err:     at com.squareup.moshi.BufferedSourceJsonReader.selectName(BufferedSourceJsonReader.java:567)
/com.omkarmoghe.pokemap W/System.err:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:147)
/com.omkarmoghe.pokemap W/System.err:     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
/com.omkarmoghe.pokemap W/System.err:     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
/com.omkarmoghe.pokemap W/System.err:     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:130)
```

**Version:**
Latest code from `Development` when building jar file and `4831b9f5653a0d7945849ab3dc028b5d728ce488` commit id from jitpack dependency.

**Comment by jabbink** [comment] 2016-07-25 11:30
> com.pokegoapi.exceptions.RemoteServerException: Received malformed response : com.google.protobuf.InvalidProtocolBufferException: CodedInputStream encountered a malformed varint.

Looks like the server returned garbage data and is unstable/offline.

**Comment by JesusM** [comment] 2016-07-25 12:14
> Looks like the server returned garbage data and is unstable/offline.

The thing is that for every attempt using the jitpack + gradle approach, I've received that error so I wasn't sure if it was a problem with the code or just bad luck/issue with server(?).

**Comment by vmarchaud** [comment] 2016-07-25 13:34
@JesusM Could you try to build it from our source to see if you get the same behavior ?

**Comment by JesusM** [comment] 2016-07-25 14:01
@vmarchaud do you mean compiling the jar file from repo's source code? If so, I've tried that approach but as I've written in the summary of this GHI, I'm receiving this error when performing one of the steps of the login flow:

```
W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=2; index=327146368
W/System.err:     at com.squareup.moshi.BufferedSourceJsonReader.selectName(BufferedSourceJsonReader.java:567)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:147)
W/System.err:     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
W/System.err:     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
W/System.err:     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
W/System.err:     at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:130)
```

Checking logs of the requests/responses received, I'm seeing some weirdness in the response when the `PtcAuthJson` is filled. This is the response received:

```






















   {
       "lt": "lt_data_here",
       "execution": "execution_data_here"





    }
```

Not sure if the fact the response's JSON contains so many `\n` characters is normal or could be related with my problem using that approach.

**Comment by jabbink** [comment] 2016-07-25 14:06
Makes sense, _technically_ that is invalid JSON, as it doesn't start with `{`, `[` or `"`.

**Comment by JesusM** [comment] 2016-07-25 15:39
Hmm, even after "cleaning" it using `replace("\n","").replace("\t","")` , I obtain the same problem ¯\_(ツ)_/¯

**Comment by FabianTerhorst** [comment] 2016-07-25 15:44
I can`t reproduce this error. Im always getting a valid json.

**Comment by rajulbhatnagar** [comment] 2016-07-25 15:46
Cant reproduce it either.

**Comment by JesusM** [comment] 2016-07-25 17:37
Unfortunately I'm not going to be able to take a look to it in the next 10 days as I'll be out so feel free to close it for now if you can't reproduce it and I'll investigate it when I come back. Maybe it's an issue related with the configuration of the okhttp client used in both API and client which generate the problem when getting the response.

**Comment by Aphoh** [comment] 2016-07-26 23:23
Closing at the request of the opener

**Closed as completed by Aphoh** 2016-07-26 23:23 UTC
Labels: question
