### ISSUE TITLE
Account banned literally right after updating the library

### ISSUE THREAD

**Issue by MrPat** [Grover-c13/PokeGOAPI-Java#656] opened 2016-08-23 03:06 UTC
I haven't updated my library for almost 2 weeks now. I decided tonight to update to the latest commit and then to PR #652. Then I build from the source and replaced the old library jar in my project. 

The first time I tried to use my scanning app after updating the jar, it kept telling me that I wasn't logged into the server even after logging in. This is a check I added, and further investigation showed that when I called `go.getMap().getCatchablePokemon();` I was getting an exception saying that my account might be banned. Attempting to login to the POGO client revealed that my scanning account was in fact banned.

Now this may sound typical but the catch is that my scanning account has been using this library for around a month now without any problems. I've been using it regularly today and it always returned Pokemon info. But as soon as I logged in after updated the library, my account was banned. I didn't even get to run a scan.

My other account (I was scanning with 2 accounts spaced equally apart in time) appears to be softbanned. It logs in but won't return any Pokemon info even from a Pokemon hotspot that I always scan to get lots of results.

What I'm trying to figure out here is why my accounts got banned after updating to the latest commit. I think the last library version I used came before the device/sensor info commits, so maybe it's because I was passing nothing for this info and then suddenly started passing values? I also started passing legitimate altitude values for my location today but it still worked for hours after that. Any ideas?

**Comment by Grover-c13** [comment] 2016-08-23 03:23
Niantic started banning heaps the last 6 hours, many people have been hit.

**Comment by ramarro123** [comment] 2016-08-23 07:38
just curious, you say "your scanning account"
means that you NEVER try to catch a pokemon or loot pokestop with that account? just scan around?

**Comment by pvanassen** [comment] 2016-08-23 10:28
This API generates requests to the Niantic server which are so much different from the actual Pokemon GO app, just logging in with this lib may get you banned.

**Comment by AbandonedCart** [comment] 2016-08-23 10:30
Used incorrectly that is true. Make sure to watch the PRs to see the progress to prevent that.

**Comment by pvanassen** [comment] 2016-08-23 10:40
Which ones? Curious to see

**Comment by chegola** [comment] 2016-08-23 11:48
My Id has been banned too since I was running this lib for 4 days. I ll get new id and try to play with this lib again :)

**Comment by Paul776** [comment] 2016-08-23 14:12
@LoungeKatt 
makes 0 difference.

**Comment by AbandonedCart** [comment] 2016-08-23 14:47
@Paul776 Talking about PRs made after the ban wave to prevent being banned in that ban wave, of course. @pvanassen Any that apply to better device identification, real or not.

**Comment by Paul776** [comment] 2016-08-23 15:30
@LoungeKatt of course. I meant that even with that perfect PR about the device and stuff. you will never have 100% the same request as the real game. thus insta-ban if they wish.

**Comment by AbandonedCart** [comment] 2016-08-23 15:42
Used incorrectly, that will always be true.

**Comment by pvanassen** [comment] 2016-08-23 15:50
Got some pr numbers for me? None of the open pr's seem to be about this.

**Comment by MrPat** [comment] 2016-08-23 16:02
Yes I realize that just using the library is cause for a ban, but I've been using it without incident for a month now. Something about updating the library immediately permabanned one account and softbanned another.

I get that there's always a ban chance but that can't be a coincidence. I'm just saying that some change in the requests must've set off huge red flags for my account to be banned immediately after the update like that. 

Again, this isn't a blame-the-library post. It's more of a "heads up, this is a thing" post. I suspect that if I create a new account and only use it with the latest library version, everything should be fine (at least as fine as it can be).

**Comment by FabianTerhorst** [comment] 2016-08-23 16:03
Many people got banned since there updated the server and the client apps.

**Comment by AbandonedCart** [comment] 2016-08-23 16:27
Detection adds you to a list of users to ban, but bans happen on a schedule. It's that simple.

The API is not intended to be a crutch. It is an interface to the server. If you get banned because of delays, device info, app signature, etc it is the responsibility of the user to be configuring those things. The API does offer defaults, but they are no replacement for configuring your own and have a short lifespan as anything more than examples. It seems a lot of time and effort is being invested in configuring the API so "any idiot can use it" but no responsibility is being taken for usage.

@pvanassen There are 7 PRs and two are different versions of the same thing. If you are unable to identify which ones relate to avoiding detection, then it is best to wait until they are merged.

**Comment by AbandonedCart** [comment] 2016-08-23 17:44
Whether or not it is the desired answer, the answer to the issue is that a ban does not happen immediately in most cases. It is the result of a past detection rolled into the current ban wave.

In short, it wasn't "updating to the latest commit" that caused it. It would have happened anyway.

**Closed as completed by AbandonedCart** 2016-08-23 17:44 UTC
