### ISSUE TITLE
Error on updateInventories

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#327] opened 2016-07-28 22:34 UTC
The program throws an exception when your itembag has more items than it can has.
It happens when you have the full inventory and then get next level, the level up bonus will give you more items than your itembag can carry and the next try to update will thrown this exception

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

**Comment by ushort** [comment] 2016-07-28 22:35
read the other issues. niantic api has changed so it needs to wait for this to be fixed

**Comment by vmarchaud** [comment] 2016-07-28 22:43
Niantic api hasnt changed. The PokemonGo servers arent working thats it. This exception is thrown when we cant parse a response from the server.

**Comment by bolds07** [comment] 2016-07-28 22:53
@vmarchaud did you tried to reproduce it? i didn't debug yet as i really dont understand the protobuf data, but this situation is pretty common i think and the oficial app can deal with it

so probably the parse method has some bug, maybe a fixed value for max amount of data received... and as the parser was automatically generated i would not doubt about it

**Comment by vmarchaud** [comment] 2016-07-28 22:58
@bolds07 i understand your question, we got error like these 1 weeks ago non-stop when the servers werent doing up/down every minutes, the issue isnt that api has changed.

Everyone should alway wait few hours before making issue to see if it persist or not, since the official server arent stable.

PS : complete stacktrace are always better than only one line.

**Comment by bolds07** [comment] 2016-07-28 23:06
@vmarchaud for sure a parser exception is thrown in several situations, but i'm describing here a example that it souldn't

I took several time to realize the error problem and reproduce it, so i'm sure this wasn't a server issue

PS. I will take one hour to re-create the situation, but i come back =D

**Comment by hmate9** [comment] 2016-07-28 23:07
I just tested this. When I had 400 items in my inventory (my limit is 350) I kept getting the error. But than I logged in with a mobile phone and deleted some items to go below the limit and than the API worked fine.

This is an issue!

**Comment by hmate9** [comment] 2016-07-28 23:08
Here is the stack trace:

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:86)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:107)

**Comment by vmarchaud** [comment] 2016-07-28 23:14
There isnt [any limit of item that the response can contains](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Inventory/InventoryDelta.proto#L9), it should parse without problem.
I cant test it now though.

**Comment by hmate9** [comment] 2016-07-28 23:17
Maybe Niantic sends a different response when there are more items than there should be?

**Comment by vmarchaud** [comment] 2016-07-28 23:19
@hmate9 You cant send other response apart those described in proto file, and if you think niantic changed it, nope, they didnt update the app so the protos hasnt changed.

**Comment by hmate9** [comment] 2016-07-28 23:20
@vmarchaud I just checked with a python API and they throw an error when the number of items is greater also. There is definitely something going on here, however I am completely foreign to protobuf.

**Comment by vmarchaud** [comment] 2016-07-28 23:22
@hmate9 can you link the line of the file that you are talking about ? cause they cant know the size of the item inventory without parsing the response ;)

**Comment by hmate9** [comment] 2016-07-28 23:26
@vmarchaud I don't mean that they throw an error BEFOREHAND. They throw an error as they are using the API to get the items.

ile "/Users/matehegedus/Downloads/pokebot/pokemongo_bot/**init**.py", line 31, in start
    self._setup_api()
  File "/Users/matehegedus/Downloads/pokebot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/matehegedus/Downloads/pokebot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

**Comment by vmarchaud** [comment] 2016-07-28 23:29
Yeah but the problem is that we cant get the actual response, how could we send an exception if we dont have any data ? 
btw working on something else to see if its what i think.

**Comment by vmarchaud** [comment] 2016-07-28 23:39
Okay so from what i saw, Niantic introduced a trottle to avoid being spammed with request, since you are spamming request on the login, we are getting instant throttled, working on a fix.

**Comment by hmate9** [comment] 2016-07-28 23:41
@vmarchaud Nice find!

**Comment by hoaiquantho** [comment] 2016-07-28 23:55
I am also getting errors pointing to the updateInventories() method call. Apparently its returning "undefined" which kicks out the error everyone is getting. 

Not sure why this started happening all of a sudden?

**Comment by vmarchaud** [comment] 2016-07-28 23:56
As i said, niantic introduced a rate-limit that we were breaking when we construct the PokemonGo instance, should be fixed in #328

!! PLEASE UPDATE YOUR PROJECT WITH THE LATEST BUILD !!

**Comment by hmate9** [comment] 2016-07-29 00:06
Awesome, now it logs in no problem. I think it would be cool to have this Java API automatically enforce a limit.

**Comment by vmarchaud** [comment] 2016-07-29 00:21
@hmate9 It would be cool yeah, but we'll to almost rewrite all the core architecture of the api, we'll discuting it tomorrow with all maintainers to see how we could do that.

**Comment by a4andy** [comment] 2016-07-29 00:23
I think what we need is a queue system to handle all the requests so we can push requests into the queue.

**Comment by vmarchaud** [comment] 2016-07-29 00:28
Yep, already done that with my bots, will still need to rewrite all the request that we are making in the api itself, maybe doing something async with callback, we will see.

**Comment by a4andy** [comment] 2016-07-29 00:31
@vmarchaud I'm about to do that right now on my bot, any suggestions on the what you used? Not looking to be spoonfed code, but still a beginner programmer and this is a great way of learning on my own.

**Comment by vmarchaud** [comment] 2016-07-29 00:37
@a4andy ConcurrentLinkedQueue for sure + a custom object containing a packet to send and a callback to call with the response.

If you want more info, i'm on slack that are in the bottom of the readme with the name name.
PS : you should wait for us to implement a new system into the api ^^

**Comment by Jasper-ketelaar** [comment] 2016-07-29 00:38
@a4andy Since all requests are instances of ServerRequest you could literally create a Queue that accepts ServerRequests and processes one by one them with a waiting period. However this would mean that you have to avoid using api methods. Right now I don't think there's an easier way than to just implement waiting times between actions, because trying to work around it would cost quite a bit of effort and would likely be a waste of time as it'd be implemented in the api in the coming days.

**Comment by husbeard** [comment] 2016-07-29 00:39
I wish I knew how to code more than I do, so I could rebuild my bot to actually work. Haha, will wait till next release.

**Comment by a4andy** [comment] 2016-07-29 00:48
Thanks guys, even though I probably wont get it fully working until the new system is implemented, it's still a great learning experience as I start looking into these tutorials.

@husbeard a quick fix I did was editing ServerRequest and adding a counter to only allow 3 requests max per second.

**Comment by RaeneDev** [comment] 2016-07-29 03:06
@a4andy Sorry to bother but what code did you add for this?

**Comment by a4andy** [comment] 2016-07-29 03:25
@RaeneDev Excuse my beginner code, this is what I came up with without needing sleep() everywhere in the main code. If there is a better way, please post it so we can all learn from it.

I have it set to 1100ms wait time, seems to work best for me.

```
while (true) {
            // if > x seconds since last request, reset counters.
            if ( (System.currentTimeMillis() - time) > 1100) {
                time = System.currentTimeMillis();
                current_request_count = 0;
                break;
            }

            if (current_request_count < max_calls_allowed_per_second)
                break;

            // Sleep if it hasn't been 1 second yet.
            Thread.sleep(100);
        }
current_request_count++;
```

**Comment by RaeneDev** [comment] 2016-07-29 03:37
@a4andy Excuse me for my even more noobiness xD I personally don't know java at all; where would this go?

**Comment by a4andy** [comment] 2016-07-29 03:51
@RaeneDev goes in the beginning of the ServerRequest constructor.

**Comment by RaeneDev** [comment] 2016-07-29 05:12
@a4andy thank you, seemed I accidentally removed some code before c:

**Comment by jinkawasaki333** [comment] 2016-07-29 05:52
@a4andy Sorry if this is a very stupid question to ask, but could you please take a look at the code here https://github.com/SwipeX/PokeMate/ and kindly let me know where I should change or add? It is using the API from PokeGOAPI. Thanksss :3

**Comment by Rimander** [comment] 2016-07-29 09:43
niantic change response?

**Comment by vmarchaud** [comment] 2016-07-29 10:02
If you got this issue, you may wait for #335 to come out OR add delay between request in your software, please make an issue on the repo that you are currently using (specially for bot) and not here, since authors of these need to fix their code to send less request per seconds.

Closing since the java api isnt the issue for now but the software that are using it, we will push a release with the async stuff as soon as it will be ready.

**Closed as completed by vmarchaud** 2016-07-29 10:02 UTC
Labels: bug
