### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by john086** [Grover-c13/PokeGOAPI-Java#124] opened 2016-07-22 12:37 UTC
Hi when invoke login i receive this response, when call new PtcLogin(http).login 

Response{protocol=http/1.1, code=503, message=Service Unavailable, url=https://sso.pokemon.com/503?locale=null}

There are problem with services ? 
The username and password that i must provide is of my google account ?

**Comment by stirante** [comment] 2016-07-22 12:38
PtcLogin is login to Pokemon Trainer Club, not google account. Also they have problems with servers. http://ispokemongodownornot.com/

**Comment by john086** [comment] 2016-07-22 12:53
Great, i understand.
i have another question, method  "catchPokemon()" use login of Pokemon Trainer Club, i can use google login ? is the same ?

**Comment by guipenedo** [comment] 2016-07-22 12:54
The example uses PTCLogin but you can use google, it's exactly the same. The only difference is when you create the AuthInfo object

**Comment by john086** [comment] 2016-07-22 12:57
Ok, i try to call method but give CATCH_ERROR, why ?

**Comment by guipenedo** [comment] 2016-07-22 12:58
That means you weren't able to catch him. It's just the same as when they break out of the pokeball on the official application. If that happens too often you're likely soft banned

**Comment by john086** [comment] 2016-07-22 13:10
I think soft blocked, because return the same error always, now i try to change location coordinates and retry.

**Comment by mjmjelde** [comment] 2016-07-22 13:20
@guipenedo CATCH_ERROR is not the same as a pokemon breaking out of a pokeball.  That is CATCH_ESCAPE.  CATCH_ERROR means there was something wrong in the request and the server was unable to process the catch at all.

**Comment by john086** [comment] 2016-07-22 14:44
ok i use the request from example  class CatchPokemonAtAreaExample.java and produce  CATCH_ERROR

**Comment by Grover-c13** [comment] 2016-07-23 15:32
Closing because p sure the issue is fixed. If not you are soft banned or out of pokeballs.

**Closed as completed by Grover-c13** 2016-07-23 15:32 UTC

**Comment by john086** [comment] 2016-07-23 18:00
ok i need update my jars or is software bug ?
