### ISSUE TITLE
[BUG] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#556] opened 2016-08-11 17:22 UTC
**Description:**
I was getting lots of java.util.ConcurrentModificationException while trying to catch pokemons and couldn't understand why, than a deep look I saw that method catchPokemonAsync(ServerRequest serverRequest) change the api.map.catchablePokemon...

catchablePokemon is a cached colletion, and probably people will itarate over it and as this may change the collection it will run in an exception

**Steps to reproduce:**
List<CatchablePokemon> temp = this.api.getMap().getCatchablePokemon();
            for (CatchablePokemon c : temp) {
                encounterPokemon(c);
            }
 //encounter pokemon is a method that only try to catch pokemons following my logic, it doesn't change any other class state

**Expected behavior:**
in my humble opinion api inner methods shouldn't update api status, this api can run smoothly even being totally unsynchronized with server, in this case the only problem will be some negative responses from server. While this kind of inner update may lead to unpredicted exceptions and also to unecessary requests.

**Actual behavior:**
private CatchResult catchPokemonAsync(ServerRequest serverRequest) throws RemoteServerException, LoginFailedException, InvalidProtocolBufferException {

[....] some code
        // pokemon is caught of flees
        if (response.getStatus() == CatchStatus.CATCH_FLEE || response.getStatus() == CatchStatus.CATCH_SUCCESS) {
            api.getMap().removeCatchable(instance);
        }

```
    // escapes
    if (response.getStatus() == CatchStatus.CATCH_ESCAPE) {
        api.getInventories().updateInventories();
    }
    CatchResult res = new CatchResult(response);
    return res;

}
```

**Version:**
  4abd6fa

**Comment by FabianTerhorst** [comment] 2016-08-11 17:24
#527

**Comment by FabianTerhorst** [comment] 2016-08-15 19:21
Duplicate of #527

**Closed as completed by FabianTerhorst** 2016-08-15 19:21 UTC
