### ISSUE TITLE
getPokemons().size() return worng number

### ISSUE THREAD

**Issue by francescoprisco** [Grover-c13/PokeGOAPI-Java#596] opened 2016-08-16 00:19 UTC
**Description:**
When i try tp get numer of pokemons in game the number is wrong.

i use 
`GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient,"USERNAME","PASSWORD");
                PokemonGo go= new PokemonGo(provider,httpClient);
                Log.d("num poke",go.getInventories().getPokebank().getPokemons().size()+"");`

The code return me 169 pokemons i have 178 pokemons. 

I use 0.4.0 lib version

**Comment by AbandonedCart** [comment] 2016-08-16 00:28
You should probably change your Gmail password. 
Even if you edit the post immediately, the preview in the slack channel only shows the original.

As for the issue, it may be the same as https://github.com/Grover-c13/PokeGOAPI-Java/issues/579

**Comment by francescoprisco** [comment] 2016-08-16 11:51
I have already changed. Sorry... Yesternday night i'm tired. When i can read a solution. Thanks

**Comment by FabianTerhorst** [comment] 2016-08-16 11:53
Duplicate of #579

**Closed as completed** 2016-08-16 11:52 UTC
